export function getTimeUntilEvent(date, endDate) {
    const now = new Date();
    const distance = new Date(date) - now;
    const seconds = Math.floor(distance / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);
    const days = Math.floor(hours / 24);
    const weeks = Math.floor(days / 7);
    const months = Math.floor(days / 30);

    if (new Date(endDate) < now) {
        return "Event finished"
    } else if (distance < 0) {
        return "Happening now";
    } else if (seconds < 60) {
        return `Starts in ${seconds} seconds`;
    } else if (minutes < 60) {
        return `Starts in ${minutes} minutes`;
    } else if (hours < 24) {
        return `Starts in ${hours} hours`;
    } else if (days <= 14) {
        return `Starts in ${days} days`;
    } else if (weeks <= 4) {
        return `Starts in ${weeks} weeks`;
    } else {
        return `Starts in ${months} months`;
    }

}

// Generated by ChatGPT